---
# tasks file for httpd

- name: Ensure httpd and firewalld are installed
  ansible.builtin.dnf:
    name: 
      - httpd
      - firewalld
    state: latest

- name: Enabled and started firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started

- name: HTTPD is started and enabled
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes
