---
- name: Only two user has access to the apache html directory
  hosts: servers
  become: true
  vars_files:
    - vars/users_vars.yml
    - vars/group_vars.yml
    - vars/html_path.yml
  roles:
    - httpd
  tasks:
    - name: Delete webadmin group (do not exist beforhand)
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: absent
    
    - name: New webadmin group
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present

    - name: Create  webadmin users
      ansible.builtin.user:
        name: "{{ item['username'] }}"
        groups: "{{ item['groups'] }}"
        state: present
        password: "{{ item['password'] | password_hash('sha512') }}" 
      loop: "{{ users }}"

    - name: Change {{ html_path }} permissions
      ansible.builtin.file:
        path: "{{ html_path }}"
        state: directory  
        owner: root
        group: "{{ group_name }}"
        mode: 0660

